spring:
  banner:
    location: 'classpath:/banner-local.txt'
  cloud:
    config:
      enabled: false

client:
  mapFromYaml:
    from: application-local.yaml
    foo.bar: baz
    'zoq.fot.pik': sc2
