spring:
  banner:
    location: 'classpath:/banner-local.txt'
  cloud:
    config:
      enabled: false

client:
  mapFromYaml:
    from:
      file: application-local.yaml
    foo.bar:
      baz: quux
      'zoq.fot.pik': sc2
